from pydantic import BaseModel, Field

class graph_state(BaseModel):
    user_query: str = Field(..., description="The user's query")
    roadmap: dict = Field(..., description="The day by day roadmap for a week generated by the LLM based on the user query.")
    sub_tasks: dict = Field(..., description="The sub tasks for each day generated by the orchestrator LLM based on the roadmap.")
    concept_map: dict = Field(..., description="The concept map having all of the concepts related to langchain generated by the orchestrator.")
    explaination: dict = Field(..., description="The explaination of the concepts in the concept map day by day. Only generated on the day the user reached on the concept not pre-generated.")
    code_example: dict = Field(..., description="The code example of the concepts in the concept map day by day. Only generated on the day the user reached on the concept not pre-generated.")
    final_response: str = Field(..., description="The final response that the user will see on the UI. Only generated on the day the user reached on the concept not pre-generated.")