"""Teaching node for explaining LangChain concepts using the Feynman technique.

This node:
1. Takes the concept_map generated by the builder
2. Creates beginner-friendly explanations for each concept
3. Provides simple, commented code examples
4. On retry (after critic fails), provides simpler explanations

The teaching approach:
- Break complex ideas into simple parts
- Use everyday analogies
- Connect concepts directly to the user's meme
- Avoid cognitive overload with short, digestible content
"""

import json
from langchain_core.messages import HumanMessage

from core.llm import get_llm
from graph.state import graph_state
from nodes.teaching.prompt import (
    EXPLANATION_PROMPT,
    CODE_EXAMPLE_PROMPT,
    SIMPLER_EXPLANATION_PROMPT,
)


def teaching_node(state: graph_state) -> dict:
    """
    Teaching node that explains LangChain concepts using the Feynman technique.

    Process:
    1. Extract concept_map from the builder's output
    2. Generate simple, beginner-friendly explanations
    3. Create commented code examples for each concept
    4. On retry (has_retried=True), use simpler explanations

    Args:
        state: Current graph state with concept_map, meme_text, and retry_count

    Returns:
        dict: Updated state with explanation and code_examples
    """
    concept_map = state.concept_map
    meme_text = state.meme_text
    user_query = state.user_query
    has_retried = state.has_retried

    # Validate we have concepts to teach
    if not concept_map:
        return _empty_response("No concepts available to teach")

    # Format concepts for the prompts
    concepts_formatted = _format_concepts(concept_map)

    # Choose teaching approach based on retry status
    if has_retried:
        # Simpler explanations for retry case
        explanation = _generate_simpler_explanation(concepts_formatted, meme_text)
        # Use same code examples (no need to regenerate)
        code_examples = _generate_code_examples(concepts_formatted, meme_text)
    else:
        # First-time explanation
        explanation = _generate_explanation(concepts_formatted, user_query, meme_text)
        code_examples = _generate_code_examples(concepts_formatted, meme_text)

    return {
        "explanation": explanation,
        "code_examples": code_examples
    }


def _format_concepts(concept_map: dict) -> str:
    """
    Format the concept_map into a readable string for prompts.

    Args:
        concept_map: Dictionary of concepts from builder

    Returns:
        str: Formatted concept descriptions
    """
    formatted_parts = []

    for key, concept in concept_map.items():
        if isinstance(concept, dict):
            name = concept.get("name", key)
            description = concept.get("description", "")
            relevance = concept.get("relevance", "")
            formatted_parts.append(
                f"- {name}: {description}"
                + (f" ({relevance})" if relevance else "")
            )

    return "\n".join(formatted_parts)


def _generate_explanation(concepts: str, user_query: str, meme_text: str) -> dict:
    """
    Generate Feynman-style explanations for each concept.

    Args:
        concepts: Formatted concept string
        user_query: Original user request
        meme_text: Generated meme text

    Returns:
        dict: Structured explanation for each concept
    """
    llm = get_llm()

    prompt = EXPLANATION_PROMPT.format(
        concepts=concepts,
        user_query=user_query,
        meme_text=meme_text
    )

    response = llm.invoke([HumanMessage(content=prompt)])
    return _parse_json_response(response.content)


def _generate_simpler_explanation(concepts: str, meme_text: str) -> dict:
    """
    Generate simpler explanations for the retry case (after critic failure).

    Args:
        concepts: Formatted concept string
        meme_text: Generated meme text

    Returns:
        dict: Simplified explanation for each concept
    """
    llm = get_llm()

    prompt = SIMPLER_EXPLANATION_PROMPT.format(
        concepts=concepts,
        meme_text=meme_text
    )

    response = llm.invoke([HumanMessage(content=prompt)])
    return _parse_json_response(response.content)


def _generate_code_examples(concepts: str, meme_text: str) -> dict:
    """
    Generate beginner-friendly code examples for each concept.

    Each example:
    - Shows minimal, working code
    - Has line-by-line comments
    - Relates to the meme generator project

    Args:
        concepts: Formatted concept string
        meme_text: Generated meme text

    Returns:
        dict: Code examples with explanations for each concept
    """
    llm = get_llm()

    prompt = CODE_EXAMPLE_PROMPT.format(
        concepts=concepts,
        meme_text=meme_text
    )

    response = llm.invoke([HumanMessage(content=prompt)])
    return _parse_json_response(response.content)


def _parse_json_response(content: str) -> dict:
    """
    Parse JSON response from LLM, handling formatting issues.

    Args:
        content: Raw LLM response

    Returns:
        dict: Parsed JSON or empty dict on failure
    """
    content = content.strip()

    # Remove markdown code blocks if present
    if content.startswith("```json"):
        content = content[7:]
    elif content.startswith("```"):
        content = content[3:]

    if content.endswith("```"):
        content = content[:-3]

    content = content.strip()

    try:
        return json.loads(content)
    except json.JSONDecodeError:
        # Return empty structure if parsing fails
        return {}


def _empty_response(reason: str) -> dict:
    """
    Create an empty response when teaching cannot proceed.

    Args:
        reason: Why teaching couldn't proceed

    Returns:
        dict: Empty explanation and code_examples with error info
    """
    return {
        "explanation": {"error": reason},
        "code_examples": {"error": reason}
    }


# Export for LangGraph
__all__ = ["teaching_node"]