"""Teaching node for explaining LangChain concepts using the Feynman technique.

This node:
1. Takes the concept_map generated by the builder
2. Creates beginner-friendly explanations for each concept
3. Provides code examples with inline comments
4. Provides comments-only code examples (study guide without actual code)
5. On retry (after critic fails), provides simpler explanations

The teaching approach:
- Break complex ideas into simple parts
- Use everyday analogies
- Connect concepts directly to the user's meme
- Avoid cognitive overload with short, digestible content
"""

import json
from langchain_core.messages import HumanMessage

from core.llm import get_llm
from graph.state import graph_state
from nodes.teaching.prompt import (
    EXPLANATION_PROMPT,
    CODE_EXAMPLE_PROMPT,
    COMMENTED_CODE_PROMPT,
    SIMPLER_EXPLANATION_PROMPT,
    TARGETED_RETRY_PROMPT,
)


def teaching_node(state: graph_state) -> dict:
    """
    Teaching node that explains LangChain concepts using the Feynman technique.

    Process:
    1. Extract concept_map from the builder's output
    2. Generate simple, beginner-friendly explanations
    3. Create commented code examples for each concept
    4. On retry (detected via assessment_for_teaching), use simpler explanations
       - If assessment_for_teaching has concept_name AND key_misunderstandings,
         use targeted re-explanation (single concept failure)
       - Otherwise use simpler explanations for all concepts (multiple failures)
       - Sets has_retried=True to mark that retry has been used

    Retry Detection:
        The node detects a retry when assessment_for_teaching contains either:
        - concept_name: Set by critic node (LangGraph) for single concept failure
        - key_misunderstandings: Set by critic node or API for assessment feedback

        Both LangGraph and API flows are supported:
        - LangGraph: Critic tests one concept at a time, sets concept_name
        - API: Tests all concepts at once, sets key_misunderstandings list

    Args:
        state: Current graph state with concept_map, meme_text, and assessment_for_teaching

    Returns:
        dict: Updated state with explanation, code_examples, and has_retried (on retry)
    """
    concept_map = state.concept_map
    meme_text = state.meme_text
    user_query = state.user_query
    assessment_for_teaching = state.assessment_for_teaching

    # Validate we have concepts to teach
    if not concept_map:
        return _empty_response("No concepts available to teach")

    # Format concepts for the prompts
    concepts_formatted = _format_concepts(concept_map)

    # Choose teaching approach based on whether this is a retry
    # A retry is triggered by the critic (LangGraph) or API setting assessment_for_teaching
    # Check for both structures:
    # - LangGraph pipeline: concept_name at top level (targeted retry)
    # - API/critic summary: key_misunderstandings present (simpler retry)
    is_retry = (
        assessment_for_teaching and
        (assessment_for_teaching.get("concept_name") or
         assessment_for_teaching.get("key_misunderstandings"))
    )

    if is_retry:
        # This is a retry - use targeted or simpler explanations
        # Check if we have specific assessment feedback from the critic
        # Use targeted re-explanation only if concept_name is available (single concept failure)
        # Otherwise use simpler explanations for all concepts (multiple failures)
        if assessment_for_teaching.get("concept_name") and assessment_for_teaching.get("key_misunderstandings"):
            # Use targeted re-explanation based on what user got wrong (single concept)
            explanation = _generate_targeted_explanation(
                concepts_formatted=concepts_formatted,
                meme_text=meme_text,
                assessment_feedback=assessment_for_teaching,
                previous_explanation=state.explanation,
                previous_code_examples=state.code_examples
            )
            code_examples = state.code_examples  # Keep same code examples
            commented_code_examples = state.commented_code_examples  # Keep same commented code
        else:
            # Simpler explanations for all concepts (multiple failures or no concept_name)
            explanation = _generate_simpler_explanation(concepts_formatted, meme_text)
            code_examples = _generate_code_examples(concepts_formatted, meme_text)
            commented_code_examples = _generate_commented_code_examples(concepts_formatted, meme_text)

        # Mark that retry has been used - critic will see this and enforce max 1 retry
        return {
            "explanation": explanation,
            "code_examples": code_examples,
            "commented_code_examples": commented_code_examples,
            "has_retried": True
        }
    else:
        # First-time explanation
        explanation = _generate_explanation(concepts_formatted, user_query, meme_text)
        code_examples = _generate_code_examples(concepts_formatted, meme_text)
        commented_code_examples = _generate_commented_code_examples(concepts_formatted, meme_text)

        return {
            "explanation": explanation,
            "code_examples": code_examples,
            "commented_code_examples": commented_code_examples
        }


def _format_concepts(concept_map: dict) -> str:
    """
    Format the concept_map into a readable string for prompts.

    Args:
        concept_map: Dictionary of concepts from builder

    Returns:
        str: Formatted concept descriptions
    """
    formatted_parts = []

    for key, concept in concept_map.items():
        if isinstance(concept, dict):
            name = concept.get("name", key)
            description = concept.get("description", "")
            relevance = concept.get("relevance", "")
            formatted_parts.append(
                f"- {name}: {description}"
                + (f" ({relevance})" if relevance else "")
            )

    return "\n".join(formatted_parts)


def _generate_explanation(concepts: str, user_query: str, meme_text: str) -> dict:
    """
    Generate Feynman-style explanations for each concept.

    Args:
        concepts: Formatted concept string
        user_query: Original user request
        meme_text: Generated meme text

    Returns:
        dict: Structured explanation for each concept
    """
    llm = get_llm()

    prompt = EXPLANATION_PROMPT.format(
        concepts=concepts,
        user_query=user_query,
        meme_text=meme_text
    )

    response = llm.invoke([HumanMessage(content=prompt)])
    return _parse_json_response(response.content)


def _generate_simpler_explanation(concepts: str, meme_text: str) -> dict:
    """
    Generate simpler explanations for the retry case (after critic failure).

    Args:
        concepts: Formatted concept string
        meme_text: Generated meme text

    Returns:
        dict: Simplified explanation for each concept
    """
    llm = get_llm()

    prompt = SIMPLER_EXPLANATION_PROMPT.format(
        concepts=concepts,
        meme_text=meme_text
    )

    response = llm.invoke([HumanMessage(content=prompt)])
    return _parse_json_response(response.content)


def _generate_targeted_explanation(
    concepts_formatted: str,
    meme_text: str,
    assessment_feedback: dict,
    previous_explanation: dict,
    previous_code_examples: dict
) -> dict:
    """
    Generate targeted re-explanation based on what user got wrong.

    This is called when the critic provides specific feedback about
    what the user misunderstood.

    Args:
        concepts_formatted: Formatted concept string
        meme_text: Generated meme text
        assessment_feedback: Feedback from critic about what user got wrong
        previous_explanation: The explanation user saw before
        previous_code_examples: The code examples user saw before

    Returns:
        dict: Targeted explanation focusing on user's misunderstandings,
              or simpler explanation if concept name matching fails
    """
    llm = get_llm()

    # Get the concept that user failed on
    concept_name = assessment_feedback.get("concept_name", "")
    key_misunderstandings = assessment_feedback.get("key_misunderstandings", [])
    suggestions = assessment_feedback.get("suggested_focus", "")

    # Find the specific concept explanation and code from previous attempt
    concept_key = None
    for key, concept in previous_explanation.items():
        if concept.get("name", "").lower() == concept_name.lower():
            concept_key = key
            break

    # If concept name matching fails, fall back to simpler explanation
    if not concept_key:
        # Couldn't find the concept in previous explanation
        # This can happen if LLM returns a different name format
        # Fall back to simpler explanation for all concepts
        return _generate_simpler_explanation(concepts_formatted, meme_text)

    # Get previous explanation and code for this concept
    prev_explanation = json.dumps(previous_explanation.get(concept_key, {}), indent=2)
    prev_code = previous_code_examples.get(concept_key, {}).get("code", "")

    # Format the assessment feedback for the prompt
    feedback_str = json.dumps({
        "concept_tested": concept_name,
        "misunderstandings": key_misunderstandings,
        "suggested_focus": suggestions
    }, indent=2)

    prompt = TARGETED_RETRY_PROMPT.format(
        concept_name=concept_name,
        assessment_feedback=feedback_str,
        previous_explanation=prev_explanation,
        previous_code_example=prev_code
    )

    response = llm.invoke([HumanMessage(content=prompt)])
    targeted_result = _parse_json_response(response.content)

    # Merge targeted explanation with the full explanation dict
    # Keep other concepts' explanations the same, update only the failed concept
    result = dict(previous_explanation)  # Copy previous explanations
    if targeted_result:
        result[concept_key] = {
            "name": targeted_result.get("concept_name", concept_name),
            "acknowledgment": targeted_result.get("acknowledgment", ""),
            "corrected_explanation": targeted_result.get("corrected_explanation", ""),
            "new_code_example": targeted_result.get("new_code_example", ""),
            "key_takeaway": targeted_result.get("key_takeaway", ""),
            "type": "targeted_retry"  # Mark as targeted retry for UI
        }

    return result


def _generate_code_examples(concepts: str, meme_text: str) -> dict:
    """
    Generate beginner-friendly code examples for each concept.

    Each example:
    - Shows minimal, working code
    - Has inline comments (# on same line as code)
    - Relates to the meme generator project

    Args:
        concepts: Formatted concept string
        meme_text: Generated meme text

    Returns:
        dict: Code examples with inline comments for each concept
    """
    llm = get_llm()

    prompt = CODE_EXAMPLE_PROMPT.format(
        concepts=concepts,
        meme_text=meme_text
    )

    response = llm.invoke([HumanMessage(content=prompt)])
    return _parse_json_response(response.content)


def _generate_commented_code_examples(concepts: str, meme_text: str) -> dict:
    """
    Generate comments-only code examples for each concept.

    Each example:
    - Contains ONLY comments (no actual code)
    - Shows step-by-step what the code would do
    - Serves as a study guide for understanding code flow
    - Relates to the meme generator project

    Args:
        concepts: Formatted concept string
        meme_text: Generated meme text

    Returns:
        dict: Commented code examples (comments only) for each concept
    """
    llm = get_llm()

    prompt = COMMENTED_CODE_PROMPT.format(
        concepts=concepts,
        meme_text=meme_text
    )

    response = llm.invoke([HumanMessage(content=prompt)])
    return _parse_json_response(response.content)


def _parse_json_response(content: str) -> dict:
    """
    Parse JSON response from LLM, handling formatting issues.

    Args:
        content: Raw LLM response

    Returns:
        dict: Parsed JSON or empty dict on failure
    """
    content = content.strip()

    # Remove markdown code blocks if present
    if content.startswith("```json"):
        content = content[7:]
    elif content.startswith("```"):
        content = content[3:]

    if content.endswith("```"):
        content = content[:-3]

    content = content.strip()

    try:
        return json.loads(content)
    except json.JSONDecodeError:
        # Return empty structure if parsing fails
        return {}


def _empty_response(reason: str) -> dict:
    """
    Create an empty response when teaching cannot proceed.

    Args:
        reason: Why teaching couldn't proceed

    Returns:
        dict: Empty explanation and code_examples with error info
    """
    return {
        "explanation": {"error": reason},
        "code_examples": {"error": reason}
    }


# Export for LangGraph
__all__ = ["teaching_node"]